
import React from 'react';
import Layout from '../../components/Layout';
import Head from 'next/head';
import Link from 'next/link';
import CourseListing from '../../components/courses/course-listing';
import courseCategorizer from '../../utils/course-categorizer';
import COURSE_LIST from '../../src/data/autogenerated_course_info.json';

export async function getStaticProps() {
  const courseList = COURSE_LIST;
  const categorizedCourses = courseCategorizer(courseList.courses);

  return {
    props: {
      courseList,
      categorizedCourses,
    },
  };
}

export default function CoursesPage({ courseList, categorizedCourses }) {
  return (
    <Layout>
      <Head>
        <title>Pitt CS Course Exploration</title>
      </Head>
      <h1>Courses</h1>
      <p>
        If you are new to the CS classes,
        <span className="ml-2 bg-yellow-300 px-2 py-1">
          we suggest viewing our{" "}
          <Link href="/academics/scheduling">scheduling guide</Link>!
        </span>
      </p>
      <CourseListing
        courseList={courseList}
        courseCategories={categorizedCourses}
      />
    </Layout>
  );
}
