
import json
import os
from backend.database.courses_db import CoursesDatabase
from backend.database.models import Course

def update_wiki_data():
    """Updates the wiki's JSON data file from the database."""
    print("Starting wiki data update...")

    db = CoursesDatabase()
    session = db.get_session()

    courses = session.query(Course).all()
    
    if not courses:
        print("No courses found in the database.")
        return

    wiki_data = {"courses": []}
    for course in courses:
        wiki_data["courses"].append({
            "id": course.code,
            "title": course.title,
            "sci_href": course.sci_href,
            "description": course.description,
            "credits": course.credits_max,  # Use credits_max for simplicity
            "requirements": course.prerequisites,
        })

    # Path to the wiki's data file
    wiki_data_path = "/Users/shreyashranjan/Library/CloudStorage/OneDrive-UniversityofPittsburgh/CSC/Dev/pittcswiki/src/data/autogenerated_course_info.json"

    try:
        with open(wiki_data_path, 'w') as f:
            json.dump(wiki_data, f, indent=2)
        print(f"Successfully updated {wiki_data_path}")
    except IOError as e:
        print(f"Error writing to {wiki_data_path}: {e}")

    session.close()
    print("Wiki data update completed.")

if __name__ == '__main__':
    update_wiki_data()
